create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name varchar(32) not null,
  message varchar(300) not null,
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

create policy "Allow read messages"
on public.messages
for select
to anon
using (true);

create policy "Allow insert messages"
on public.messages
for insert
to anon
with check (
  char_length(name) between 1 and 32
  and char_length(message) between 1 and 300
);
